# Generated by Django 4.0 on 2021-12-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgBot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
